<?php

use Illuminate\Support\Facades\Storage;
use wapmorgan\MediaFile\MediaFile;
use wapmorgan\Mp3Info\Mp3Info;
use Illuminate\Support\Str;

if(! function_exists('get_audio_duration')) {
    function get_audio_duration(string $path): string
    {
        if(Str::endsWith($path,
        'wav')) {
            $audio = MediaFile::open($path)->getAudio();
            $duration = $audio->getLength();
        } else {
            $audio = new Mp3Info($path);
            $duration = $audio->duration;
        }

        $audioMins = floor($duration / 60);
        $audioSeconds = floor($duration % 60);

        $audioMins = $audioMins > 9 ? $audioMins : '0' . $audioMins;
        $audioSeconds = $audioSeconds > 9 ? $audioSeconds : '0' . $audioSeconds;

        return $audioMins . ':' . $audioSeconds;
    }
}

if(! function_exists('get_file_with_storage_driver_path')) {
    function get_storage_driver_path(string $path): string
    {
        return Storage::disk('local')->getDriver()->getAdapter()->getPathPrefix() .'/' . $path;
    }
}

function replace_special_alphabets($string)
{
    $replaceableAlphabets = [
        'á' => 'a',
        'Á' => 'A',
        'à' => 'a',
        'À' => 'A',
        'ă' => 'a',
        'Ă' => 'A',
        'â' => 'a',
        'Â' => 'A',
        'å' => 'a',
        'Å' => 'A',
        'ã' => 'a',
        'Ã' => 'A',
        'ą' => 'a',
        'Ą' => 'A',
        'ā' => 'a',
        'Ā' => 'A',
        'ä' => 'ae',
        'Ä' => 'AE',
        'æ' => 'ae',
        'Æ' => 'AE',
        'ḃ' => 'b',
        'Ḃ' => 'B',
        'ć' => 'c',
        'Ć' => 'C',
        'ĉ' => 'c',
        'Ĉ' => 'C',
        'č' => 'c',
        'Č' => 'C',
        'ċ' => 'c',
        'Ċ' => 'C',
        'ç' => 'c',
        'Ç' => 'C',
        'ď' => 'd',
        'Ď' => 'D',
        'ḋ' => 'd',
        'Ḋ' => 'D',
        'đ' => 'd',
        'Đ' => 'D',
        'ð' => 'dh',
        'Ð' => 'Dh',
        'é' => 'e',
        'É' => 'E',
        'è' => 'e',
        'È' => 'E',
        'ĕ' => 'e',
        'Ĕ' => 'E',
        'ê' => 'e',
        'Ê' => 'E',
        'ě' => 'e',
        'Ě' => 'E',
        'ë' => 'e',
        'Ë' => 'E',
        'ė' => 'e',
        'Ė' => 'E',
        'ę' => 'e',
        'Ę' => 'E',
        'ē' => 'e',
        'Ē' => 'E',
        'ḟ' => 'f',
        'Ḟ' => 'F',
        'ƒ' => 'f',
        'Ƒ' => 'F',
        'ğ' => 'g',
        'Ğ' => 'G',
        'ĝ' => 'g',
        'Ĝ' => 'G',
        'ġ' => 'g',
        'Ġ' => 'G',
        'ģ' => 'g',
        'Ģ' => 'G',
        'ĥ' => 'h',
        'Ĥ' => 'H',
        'ħ' => 'h',
        'Ħ' => 'H',
        'í' => 'i',
        'Í' => 'I',
        'ì' => 'i',
        'Ì' => 'I',
        'î' => 'i',
        'Î' => 'I',
        'ï' => 'i',
        'Ï' => 'I',
        'ĩ' => 'i',
        'Ĩ' => 'I',
        'į' => 'i',
        'Į' => 'I',
        'ī' => 'i',
        'Ī' => 'I',
        'ĵ' => 'j',
        'Ĵ' => 'J',
        'ķ' => 'k',
        'Ķ' => 'K',
        'ĺ' => 'l',
        'Ĺ' => 'L',
        'ľ' => 'l',
        'Ľ' => 'L',
        'ļ' => 'l',
        'Ļ' => 'L',
        'ł' => 'l',
        'Ł' => 'L',
        'ṁ' => 'm',
        'Ṁ' => 'M',
        'ń' => 'n',
        'Ń' => 'N',
        'ň' => 'n',
        'Ň' => 'N',
        'ñ' => 'n',
        'Ñ' => 'N',
        'ņ' => 'n',
        'Ņ' => 'N',
        'ó' => 'o',
        'Ó' => 'O',
        'ò' => 'o',
        'Ò' => 'O',
        'ô' => 'o',
        'Ô' => 'O',
        'ő' => 'o',
        'Ő' => 'O',
        'õ' => 'o',
        'Õ' => 'O',
        'ø' => 'oe',
        'Ø' => 'OE',
        'ō' => 'o',
        'Ō' => 'O',
        'ơ' => 'o',
        'Ơ' => 'O',
        'ö' => 'oe',
        'Ö' => 'OE',
        'ṗ' => 'p',
        'Ṗ' => 'P',
        'ŕ' => 'r',
        'Ŕ' => 'R',
        'ř' => 'r',
        'Ř' => 'R',
        'ŗ' => 'r',
        'Ŗ' => 'R',
        'ś' => 's',
        'Ś' => 'S',
        'ŝ' => 's',
        'Ŝ' => 'S',
        'š' => 's',
        'Š' => 'S',
        'ṡ' => 's',
        'Ṡ' => 'S',
        'ş' => 's',
        'Ş' => 'S',
        'ș' => 's',
        'Ș' => 'S',
        'ß' => 'SS',
        'ť' => 't',
        'Ť' => 'T',
        'ṫ' => 't',
        'Ṫ' => 'T',
        'ţ' => 't',
        'Ţ' => 'T',
        'ț' => 't',
        'Ț' => 'T',
        'ŧ' => 't',
        'Ŧ' => 'T',
        'ú' => 'u',
        'Ú' => 'U',
        'ù' => 'u',
        'Ù' => 'U',
        'ŭ' => 'u',
        'Ŭ' => 'U',
        'û' => 'u',
        'Û' => 'U',
        'ů' => 'u',
        'Ů' => 'U',
        'ű' => 'u',
        'Ű' => 'U',
        'ũ' => 'u',
        'Ũ' => 'U',
        'ų' => 'u',
        'Ų' => 'U',
        'ū' => 'u',
        'Ū' => 'U',
        'ư' => 'u',
        'Ư' => 'U',
        'ü' => 'ue',
        'Ü' => 'UE',
        'ẃ' => 'w',
        'Ẃ' => 'W',
        'ẁ' => 'w',
        'Ẁ' => 'W',
        'ŵ' => 'w',
        'Ŵ' => 'W',
        'ẅ' => 'w',
        'Ẅ' => 'W',
        'ý' => 'y',
        'Ý' => 'Y',
        'ỳ' => 'y',
        'Ỳ' => 'Y',
        'ŷ' => 'y',
        'Ŷ' => 'Y',
        'ÿ' => 'y',
        'Ÿ' => 'Y',
        'ź' => 'z',
        'Ź' => 'Z',
        'ž' => 'z',
        'Ž' => 'Z',
        'ż' => 'z',
        'Ż' => 'Z',
        'þ' => 'th',
        'Þ' => 'Th',
        'µ' => 'u',
        'а' => 'a',
        'А' => 'a',
        'б' => 'b',
        'Б' => 'b',
        'в' => 'v',
        'В' => 'v',
        'г' => 'g',
        'Г' => 'g',
        'д' => 'd',
        'Д' => 'd',
        'е' => 'e',
        'Е' => 'E',
        'ё' => 'e',
        'Ё' => 'E',
        'ж' => 'zh',
        'Ж' => 'zh',
        'з' => 'z',
        'З' => 'z',
        'и' => 'i',
        'И' => 'i',
        'й' => 'j',
        'Й' => 'j',
        'к' => 'k',
        'К' => 'k',
        'л' => 'l',
        'Л' => 'l',
        'м' => 'm',
        'М' => 'm',
        'н' => 'n',
        'Н' => 'n',
        'о' => 'o',
        'О' => 'o',
        'п' => 'p',
        'П' => 'p',
        'р' => 'r',
        'Р' => 'r',
        'с' => 's',
        'С' => 's',
        'т' => 't',
        'Т' => 't',
        'у' => 'u',
        'У' => 'u',
        'ф' => 'f',
        'Ф' => 'f',
        'х' => 'h',
        'Х' => 'h',
        'ц' => 'c',
        'Ц' => 'c',
        'ч' => 'ch',
        'Ч' => 'ch',
        'ш' => 'sh',
        'Ш' => 'sh',
        'щ' => 'sch',
        'Щ' => 'sch',
        'ъ' => '',
        'Ъ' => '',
        'ы' => 'y',
        'Ы' => 'y',
        'ь' => '',
        'Ь' => '',
        'э' => 'e',
        'Э' => 'e',
        'ю' => 'ju',
        'Ю' => 'ju',
        'я' => 'ja',
        'Я' => 'ja'
    ];
    return str_replace(
        array_keys(
            $replaceableAlphabets
        ),
        array_values($replaceableAlphabets),
        $string);
}

function getData()
{
    return array(
        array('title' => 'Tawheeds Dygder (7 min)','created_by_alias' => 'Abu Dawud Abdullah as-Sueidi'),
        array('title' => 'Tappa inte hoppet (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => '5 villkor för att synda (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => '10 första dagarna i Dhul Hijjah (10 min)','created_by_alias' => 'Abu Dawud Abdullah as-Sueidi'),
        array('title' => 'Fast på religionen (3 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Så följer man Profeten (sallâ Allâhu \'alayhi wa sallam) (6 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Dygderna av La ilaha illa Allah (7 min)','created_by_alias' => 'Abu Dawud Abdullah as-Sueidi'),
        array('title' => 'Eid al Adha (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Inbrottstjuven & Imamen (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'En vacker hadith om kunskapens dygder (7 min)','created_by_alias' => 'Abu Dawud Abdullah as-Sueidi'),
        array('title' => 'Varför lever du? (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Meningen med din existens (9 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Helgade månaden al-Muharram (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Baktal (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Dina val & hur de påverkar dig (6 min) ','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Den sista medlingen (5 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Shirk - den värsta synden (9 min)','created_by_alias' => 'Abu Dawud Abdullah as-Sueidi'),
        array('title' => 'Glimtar från Sahabas liv - Stadfasthet  (6 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Högmod (5 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Glimtar från Sahabas liv - Sunnah (7 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vikten av att lära sig arabiska (6 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Terrorattackerna i Paris (7 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Den mindre formen av shirks fara (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vikten av äktenskap (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Glimtar från Sahabas liv - Bönen (8 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Hur går ett äktenskap till i Islam? (10 min) ','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnet Allah (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Sunnan är som Noas ark (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Makans rättigheter - Del 1 (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Makans rättigheter - Del 2 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Faran med innovationer (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Makens rättigheter - Del 1 (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vad är Islam?  (12 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Jesus - Guds tjänare & Sändebud (11 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Makens rättigheter - Del 2 (12 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vikten av att lära sig om Allahs namn & attribut (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vägarna till kriminalitet (12 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur ska vi tro på Allahs namn & attribut (10 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Att ständigt minnas Allah (6 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Del 1 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ett kliv mot ett nytt liv - Koranen (14 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnet ar-Rabb (6 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Luras inte av dig själv (7 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Var förlåtande (8 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Ett kliv mot ett nytt liv - Del 3 (11 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnen ar-Rahman ar-Rahim (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Känn dig inte säker från Allahs straff (12 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Del 4 (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnen al-Hayy al-Qayyum (6 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Livet i graven (6 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Synd & Olydnad - Del 5 (13 min) ','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnet ar-Razzaq (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Uppriktighet till Allah (10 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Alkohol - Del 6 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ett kliv mot ett nytt liv - Självmord - Del 7 (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnet as-Sami\' (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vi och Koranen (8 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Att våga förändras - Del 8 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vägen till ånger (9 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Betydelsen av namnet al-Basir (5 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vägen till förlåtelse - Del 2 (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Betydelsen av namnet al-\'Alîm (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Ett kliv mot ett nytt liv - Muslim i Sverige 2016 - Del 9 (17 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Betydelsen av namnen al-\'Afuww & al-Ghafûr (7 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'De vill släcka Allahs ljus (15 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Syrien brinner (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Månaden Sha\'bân (9 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Råd inför Ramadan (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Råd inför Ramadan - Del 2 (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Mitten av månaden Sha\'ban (10 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Råd inför Ramadan - Del 3 (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Råd inför Ramadan - Del 4 (5 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vad är syftet med skapelsen? (5 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Åkalla endast Allah! (4 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Fortsätta praktisera efter Ramadan (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'All dyrkan för Allah! (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Avguderi förstör alla handlingar! (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tawheeds 3 kategorier (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Fastan i ett orent tillstånd (6 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Att kräkas, bryter det fastan? (3 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Bryter synder fastan? (4 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Sover bort Ramadan (4 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Ramadan är en speciell månad (5 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Förändringens månad (7 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Från mörker till ljus (6 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Tålamod med allt (6 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Sök hjälp med bönen (7 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Tacksamhet och dhikr (6 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Från synder till lydnad (5 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Tafsir från surat Al-Furqan (6 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Tafsir från surat Al-Furqan - Del 2 (8 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Tafsir från surat Al-Furqan - Del 3 (5 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Tafsir från surat Al-Furqan - Del 4 (6 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Tafsir från surat Al-Furqan - Del 5 (7 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Om Eid: Bestämmelser & Profetiska vägledningar (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Medan vi faller (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Profetens Sunnah (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Föräldrarnas & de äldres status i islam (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Handlingarnas villkor (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Glimtar från Profetens karaktär (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Glimtar från Profetens karaktär - Del 2 (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Allahs vackra namn - Al-Wadud (8 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Glimtar från Profetens karaktär - Del 3 (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Allahs vackra namn - al-Kafi & al-Hasib (10 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'De första 10 dagarna i Dhul-Hidjah (12 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'De lärdas status (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vad hände efter Ramadan? (8 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Eid ul-Adha (13 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Allah är ovanför sin skapelse (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ärlighet (10 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Ärlighet - Del 2 (9 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Den helgade månaden Muharram (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ärlighet - Del 3 (10 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Ärlighet i handel - Del 4 (15 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Kampen till Jannah (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Religionen är Nasihah (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'De 3 första som hamnar i elden (9 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Vikten av Du\'a (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Trosbekännelsens 7 villkor (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Den korrekta trosläran (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Att lära sig om trosläran är obligatoriskt (10 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Dyrkan i Islam (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vägarna till ett lyckligt liv (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Att kalla till den korrekta trosläran (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Hur man hanterar ilska (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Medan vi faller - Skjutningar & Mord (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ska man fira Profetens födelsedag? (11 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Bortglömda Sunnah (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Dagliga handlingar som hör till Sunnah (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Dagliga handlingar som hör till Sunnah - Del 2 (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Dagliga handlingar som hör till Sunnah - Del 3 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tawhid ar-Rububiyyah (11 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Tawhid al-Uluhiyyah (12 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Faran i att åkalla andra än Allah (4 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Avguderi förstör alla handlingar (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'All drykan hör endast till Allah (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur Tawhids kategorier hör ihop med varandra (10 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Koranens kall till Tawhid (12 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Bönen! Bönen! (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur uppkom Shirk (12 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Vägarna till Shirk - Del 1 (11 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Viktiga Dua (8 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Viktiga Dua - Del 2 (7 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Viktiga Dua - Del 3 (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Inför Ramadan - 2017  (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ett råd till muslimer efter attentatet i Stockholm (9 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => 'Fastans Fördelar (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vad bryter och vad bryter inte fastan? (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'När börjar och slutar Ramadan? (12 min)','created_by_alias' => 'Abdullah as-Sueidi'),
        array('title' => '6 nyttor med att ha Gudsfruktan (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Syftet med fastan i Ramadan (11 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'De gudfruktiges egenskaper (9 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Hur kan vi uppnå gudsfruktan? (11 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Frukta Allah och ge inte upp (7 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Döden och den intelligenta (11 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Vägen till gudsfruktan (11 min)','created_by_alias' => 'Yusef as-Sueidi'),
        array('title' => 'Ramadan - Koranens månad (12 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Hur Allah ärar och upphöjer folk med Koranen (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Koranen: En skatt av belöning och kunskap (13 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Förträffligheten av vissa kapitel och verser från Koranen (12 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Förträffligheten av vissa kapitel och verser från Koranen - Del 2 (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Hur ska man läsa Koranen? (13 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Förklaring av trons grunder - Del 2 (12 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Förklaring av trons grunder - Del 3 (13 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Förklaring av trons grunder - Del 4 (13 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Varför finns du? (2 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Tiden (2 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Att följa Profetens Sunnah (2 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Fällor i Ramadan (2 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Tron på sista dagen (11 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Avsluta Ramadan på bästa sätt (5 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ta vara på sista dagarna i Ramadan (3 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Att praktisera islam även efter Ramadan (7 min) ','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Qadr (13 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Dygden av goda handlingar (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Älskar du Allah? (2 min)','created_by_alias' => 'Imran Sheikh'),
        array('title' => 'Dygden av goda handlingar - Del 2 (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Dygden av goda handlingar - Del 3 (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'De tio första dagarna i Dhul-Hijjah (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Människornas liknelse i detta liv (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Hur uppnår man inlevelse i Bönen? (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Mest älskade handlingarna hos Allah (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'De tidiga imamernas bön (6 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Berättelsen om pärlhalsbandet (10 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Koranens väldigaste Surah (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Drömmar (10 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Mawlid (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'al-Aqsa i våra hjärtan (10 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Jesus sanna budskap (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Tips för bättre sömn enligt Sunnah (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tips för bättre sömn enligt Sunnah - Del 2 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tre vackra råd (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Ta vara på din hälsa (12 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Lär känna Allah (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Varför besvaras inte min dua (6 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Sju farliga konsekvenser av synder (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Vanliga misstag man säger och gör (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => '7 enkla sätt du kan bekämpa islamhatet på sociala medier (12 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Några tips kring barnuppfostran (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur kan jag förbättra min bön (8 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Råd inför Ramadan 2018 (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Visdomen bakom fastan (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vanliga misstag i Ramadan (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur ska vi välkomna Ramadan (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Målet med fastan (11 min)','created_by_alias' => ''),
        array('title' => 'De gudsfruktigas egenskaper (9 min)','created_by_alias' => ''),
        array('title' => 'Vad har du förberett till Domedagen (10 min)','created_by_alias' => ''),
        array('title' => 'Rädda dig från elden (10 min)','created_by_alias' => ''),
        array('title' => 'Tron på Allah (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Änglarna (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Böckerna (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Sändebuden (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Domedagen & Ödet (12 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Hur kan vi öka vår tro på Allah (9 min) ','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Hur kan vi öka vår tro på Allah - Del 2 (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Hur kan vi öka vår tro på Allah - Del 3 (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Hur kan vi öka vår tro på Allah - Del 4 (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => '10 sista dagarna (4 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Laylat ul-Qadr (7 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Att tänka på när man gör dua (8 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Skänk ifrån det du älskar (11 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Berättelsen om den blinde, den spetälske och den flintskallige (17 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Föräldrarnas status i Islam (7 min) ','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Varför ber du inte? Svar på de vanligaste ursäkterna (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'At-Tawakkul - Att lita på Allah (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Skatter bättre än guld och silver (15 min)','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'Balans i dyrkan (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Faran i att förtrycka någon (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Skynda till gott (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Bli förlåten 1 års synder under Ashura dagen (4 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vi måste ha tålamod (9 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => '9 faktorer som får bort shaytan (8 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'De fyra mest älskade orden hos Allah (10 min) ','created_by_alias' => 'Abdul-Wadud as-Sueidi'),
        array('title' => 'O Allah, hjälp mig minnas dig... (8 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Ett råd till ungdomar kring droger & kriminalitet (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Vad betyder Shahadah (Trosbekännelsen)? (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Vad betyder "ilah" (Gudom) i trosbekännelsen? (7 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Vad betyder La ilah illa Allah (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Några av trosbekännelsens dygder (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Villkoren för La ilah illa Allah (11 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Vad går emot La ilah illa Allah (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Felaktiga förståelser av La ilaha illa Allah (8 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => 'Islamofobin  (13 min)','created_by_alias' => 'Abu Dawud as-Sueidi'),
        array('title' => '5 tips inför Ramadan (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Ett gyllene råd ifrån profeten till Abu Dharr (7 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Ramadan - Förändringen börjar här och nu idag! (7 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Målet med fastan i Ramadan (11 min)','created_by_alias' => 'Yosuf as-Sueidi'),
        array('title' => 'Vilka egenskaper har de gudfruktiga? (9 min)','created_by_alias' => 'Yosuf as-Sueidi'),
        array('title' => 'Vad har du förberett inför Domedagen? (10 min)','created_by_alias' => 'Yosuf as-Sueidi'),
        array('title' => 'Hur viktigt är vårt tal och vad vi säger? (10 min)','created_by_alias' => 'Yosuf as-Sueidi'),
        array('title' => 'Tron på Allah (10 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Änglarna (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Böckerna (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Sändebuden (7 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Domedagen (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tron på Ödet (6 min)','created_by_alias' => 'Moosa Assal'),
        array('title' => 'Tillit till Allah (12 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'La ilaha illa Allah (7 min)','created_by_alias' => 'Abu Junayd'),
        array('title' => 'Bönen (14 min)','created_by_alias' => 'Sadiq Somali'),
        array('title' => 'Zakat (15 min)','created_by_alias' => 'Abu Makiyah'),
        array('title' => 'Sadaqah (18 min) ','created_by_alias' => 'Abu Makiyah')
    );
}
